import Head from "next/head";
import { FC } from "react";
import { TRail } from "../../../domain/Rail";
import Rail from "../../components/Rail";
import styles from "./index.module.scss";

type TProps = {
  homeRails: TRail[];
};

const HomePage: FC<TProps> = ({ homeRails }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Movie Catalog</h1>

        {homeRails.map((rail) => (
          <Rail key={`rail-${rail.name}`} {...rail} />
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default HomePage;
